### ISSUE TITLE
[Bug] Identity is not populated with Signed in user upon workflow termination

### ISSUE THREAD

**Issue by Sun-ship-it** [temporalio/web#291]
**Describe the bug**
Identity is not populated with Signed in user upon workflow termination

**To Reproduce**
1. Go to 'Temporal Web' using SSO option.
2. Click on 'workflow'
3. Terminate it. In the pop up mention the reason for termination.

**Expected behavior**
I was hoping identity will be mine based upon SSO. But, instead it came up as empty.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can also use [Loom](http://loom.com/) to do short video bug reports.

**Desktop (please complete the following information where relevant):**
 - OS: iOS
 - Browser: Chrome
 - Temporal Web Version ?
- Temporal SaaS

**Comment by sw-yx** [comment]
hey Sunny,

- we discussed this today and consider it a feature request rather than bug
- the system doesnt make decisions based on identity field, this reason for termination field is purely for audit purposes
- we are not clear what you mean when you talk about "identity" - when you say "instead it came up as empty", what exactly do you mean? maybe a screenshot would help.
